name: del_rips_sleep_wake_classification
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - pip=20.2.3  # this version of pip is needed because cechmate uses phat which has issues installing using newer versions of pip
  - pip:
    - matplotlib==3.6.1
    - numpy==1.23.4
    - pandas==1.5.1
    - scipy==1.9.3
    - scikit-learn==1.1.3
    - cython==0.29.32
    - ripser==0.6.4
    - pybind11==2.10.1
    - jupyter