name: del_rips_sleep_wake_classification
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.2.3  # this version of pip is needed because cechmate uses phat which has issues installing using newer versions of pip
  - pip:
    - matplotlib==3.1.3
    - numpy==1.19.5
    - pandas==1.1.5
    - scipy==1.5.2
    - sklearn==1.1.3
    - cython
    - ripser==0.6.4
    - pingouin==0.3.4
    - jupyter